### ISSUE TITLE
Selected date passed to view has to be midnight / zero-hour value

### ISSUE THREAD

**Issue by fredcy** [justinmimbs/elm-date-selector#1]
I tried your date selector and like it a lot.

The one thing I tripped over is that the "selected" date passed to the view function has to be a midnight / zero-hour value. I used `Date.now` to get the current date-time and when I pass that value to the view the current date is not highlighted on the full month calendar. If I use your `Date.Extra.floor` function to truncate it to the nearest Day then it works fine.

So I suggest that you either mention this in the documentation, or possibly change the view so it does the floor calculation itself.

**Comment by justinmimbs** [comment]
Thanks, Fred! :+1:  I'll fix this and publish an update....

**Comment by justinmimbs** [comment]
Thanks again, Fred! This is now fixed in 1.0.1.

**Comment by fredcy** [comment]
Looks good to me.
